---
# Install Prometheus Node Exporter
- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/node_exporter

- name: Create node_exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target

- name: Start and enable node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started

# Enable Geth metrics if not already
- name: Ensure Geth Docker container is restarted with metrics enabled
  docker_container:
    name: ethereum-node
    image: ethereum/client-go:stable
    state: started
    restart_policy: always
    ports:
      - "30303:30303"
      - "8545:8545"
      - "6060:6060"
    command: >
      --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3" --metrics --metrics.addr "0.0.0.0" --metrics.port 6060
