---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install basic utilities
  apt:
    name:
      - curl
      - git
      - ufw
    state: present

- name: Set UFW (firewall) default policies
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow Ethereum P2P port
  ufw:
    rule: allow
    port: 30303
    proto: tcp
